language: generic
sudo: required

services:
 - docker

before_install:
 - docker build -t sridevi09/docker-react -f DockerFile.dev .

script:
 - docker run -e CI=true sridevi09/docker-react npm run test